# Etapa 1: Construção da aplicação
FROM node:latest AS build

WORKDIR /app

# Copie package.json e package-lock.json (ou yarn.lock)
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante do código e construa a aplicação
COPY . .
RUN npm run build

# Etapa 2: Servir a aplicação com um servidor web leve (por exemplo, nginx)
FROM nginx:alpine

# Remova o conteúdo padrão do nginx
RUN rm -rf /usr/share/nginx/html/*

# Copie a aplicação construída para o diretório do nginx
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exponha a porta que o nginx usará
EXPOSE 80