# Use uma imagem Node para construir e rodar a aplicação NestJs
FROM node:latest AS build

# Define o diretório de trabalho no container
WORKDIR /app
# WORKDIR /usr/src/app

# Copie package.json e package-lock.json (ou yarn.lock)
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o código fonte
COPY . .

# Compile o TypeScript
RUN npm run build

# Exponha a porta que o NestJs utilizará (por exemplo, 3000)
EXPOSE 3000

# Inicie a aplicação
CMD ["npm", "run", "start:prod"]